#!/usr/bin/env python

import sys
from pathlib import Path
import subprocess
import urllib.request
import re
from time import sleep
import paramiko

RDP_COMMAND = "xfreerdp"
MULTI_MONITOR_MODE_ARG = "+span" # "+span" or "/multimon" or None
WINDOWS_USERNAME = "roger"
WINDOWS_PASSWORD = "admin"
SEND_NOTIFICATIONS = True # requires notify-send to be installed
AUTO_SHUTDOWN_CONTAINER = True

CONTAINER_NAME = "WinBoat"
IP = "127.0.0.1"
HOME_PATH = Path.home()
WINDOWS_HOME_PATH = "\\\\host.lan\\Data"

def send_notification(message):
    print(message)
    if SEND_NOTIFICATIONS:
        subprocess.run(["notify-send", "Auto WinBoat", message])

def get_port_mapping_from_port_output(port_output):
    return {
        "api": re.search(r"7148/tcp -> (.*):(.*)", port_output).group(2),
        "rdp": re.search(r"3389/tcp -> (.*):(.*)", port_output).group(2),
        "ssh": re.search(r"22/tcp -> (.*):(.*)", port_output).group(2)
    }

def convert_linux_path_to_windows_path(linux_path):
    path = Path(linux_path).resolve()
    if HOME_PATH not in path.parents:
        send_notification(f"Can't open {path}; not in home directory!")
        raise Exception()
    path_from_home = str(path)[len(str(HOME_PATH)):].replace("/", "\\")
    return WINDOWS_HOME_PATH + path_from_home

def convert_args(file_arg_positions, args):
    if file_arg_positions != 0: # convert linux file paths to Windows file paths
        file_arg_positions = list(map(lambda arg: int(arg) - 4, file_arg_positions.split(",")))
        for arg_position in file_arg_positions:
            args[arg_position] = convert_linux_path_to_windows_path(args[arg_position])

    return " ".join(args)

def start_container():
    return subprocess.run(["docker", "container", "start", CONTAINER_NAME], stdout = subprocess.DEVNULL, stderr = subprocess.DEVNULL)

def stop_container():
    return subprocess.run(["docker", "container", "stop", CONTAINER_NAME], stdout = subprocess.DEVNULL, stderr = subprocess.DEVNULL)

def check_health(api_port, timeout = 15):
    is_healthy = False
    seconds_elapsed = 0
    while(not is_healthy and seconds_elapsed < timeout):
        try:
            with urllib.request.urlopen(f"http://{IP}:{api_port}/health") as res:
                if res.status == 200:
                    is_healthy = True
                else:
                    raise Exception()
        except:
            sleep(1)
        finally:
            seconds_elapsed += 1
    return is_healthy

def launch_app_via_remoteapp(rdp_port, executable, args):
    print(f"Launching {executable}...")
    command = [
        RDP_COMMAND,
        "/cert:ignore",
        "+clipboard",
        "/sound:sys:pulse",
        "/microphone:sys:pulse",
        "/floatbar",
        "/compression",
        "/sec:tls",
        f"/u:{WINDOWS_USERNAME}",
        f"/p:{WINDOWS_PASSWORD}",
        "/v:127.0.0.1",
        f"/port:{rdp_port}",
    ]
    if executable == "desktop":
        command += [
            "+f",
            "/scale:100"
        ]
    else:
        command += [
            "-wallpaper",
            "/scale-desktop:100",
            "/wm-class:winboat-yay",
            f"/app:program:{executable},cmd:{args}"
        ]
        if MULTI_MONITOR_MODE_ARG:
            command.append(MULTI_MONITOR_MODE_ARG)
    rdp_process = subprocess.Popen(command, stdout = subprocess.DEVNULL, stderr = subprocess.DEVNULL)
    print(f"Launched {executable}!")

def wait_to_shut_down_container(ssh_port):
    print("Waiting for RDP and / or WinBoat to close...")
    ssh = paramiko.SSHClient()
    ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    ssh.connect(IP, ssh_port, WINDOWS_USERNAME, WINDOWS_PASSWORD)

    while True:
        sleep(5)

        xwininfo_process = subprocess.run(["xwininfo", "-root", "-children"], capture_output = True, text = True)
        if xwininfo_process.stdout.find("WinBoat") != -1:
            continue

        _, stdout, _ = ssh.exec_command("tasklist /v")
        lines = stdout.readlines()

        is_rdp_still_open = False
        for line in lines:
            if line.find("RDP-Tcp") != -1:
                is_rdp_still_open = True
                break
        if not is_rdp_still_open:
            return

def main(executable, args):
    send_notification(f"Starting {executable}...")
    print("Starting container...")
    start_container_process = start_container()
    if start_container_process.returncode != 0:
        send_notification("Error starting container!")
        return
    print("Container is running!")

    get_ports_process = subprocess.run(["docker", "container", "port", CONTAINER_NAME], capture_output = True, text = True)
    port_mapping = get_port_mapping_from_port_output(get_ports_process.stdout)

    is_healthy = check_health(port_mapping["api"])
    if not is_healthy:
        send_notification(f"Container isn't healthy; can't start {executable}!")
        if AUTO_SHUTDOWN_CONTAINER:
            stop_container()
        return
    print("Container is healthy!")

    launch_app_via_remoteapp(port_mapping["rdp"], executable, args)

    if AUTO_SHUTDOWN_CONTAINER:
        wait_to_shut_down_container(port_mapping["ssh"])
        print("Shutting down container...")
        stop_container()
        send_notification("Container shutdown successfully!")

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: auto-winboat\n\t<path_to_executable_on_windows>\n\t<comma_separated_file_arg_positions>\n\t<arguments_to_executable>\n")
        print("Ex. auto-winboat \"C:\\program.exe\" 5,6 arg1 \"./image_1.png\" \"./image_2.png\"")
        print("would execute C:\\program.exe arg1 C:\\path\\to\\image_1.png C:\\path\\to\\image_2.png")
        print("Use 0 if you don't want to convert any file paths'")
    else:
        if len(sys.argv) == 2:
            main(sys.argv[1], [])
        else:
            args = convert_args(sys.argv[2], sys.argv[3:])
            main(sys.argv[1], args)
